public enum Units
{
    HwanPioneer,
    HwanBrainwashedEmuKnight,
    HwanDecentralizedMilitary,
    HwanSpy,
    HwanUnicornOrder,
    HwanLEO,
    HwanJediKnight,
    HwanProtoNinja,
    HwanJackieChan,
    FinnoPioneer,
    FinnoEmuHorseArcher,
    FinnoDecentralizedMilitary,
    FinnoSpy,
    FinnoElephantCavarly,
    FinnoAncientSorcerer,
    FinnoJediKnight,
    FinnoAutismBeamDrone,
    FinnoGenghisKhan
}